### ISSUE TITLE
Programming Model v4 deployments

### ISSUE THREAD

**Issue by JonSilver** [AlexPshul/nxazure#30]
Has anyone had any luck getting their `@nxazure/func` projects to deploy? We've tried GitHub actions and the VSCode Azure Extension, but even when it appears to have been deployed successfully, there are no functions recognised by the function app. But it all runs just fine locally using the `:start` target. We're using the new Programming Model v4 with Typescript code.

**Comment by AlexPshul** [comment]
Hi Jon,
I'd be happy to help you figure this out.
In my project, I'm publishing the functions via GitHub actions.
One of the things that the package provides is the ability to also publish it to the cloud.

Simply use the executor `publish` to do so. :)
Here is the nx console command:
`npx nx publish my-nx-app-name -n my-deployed-func-app-name`

For GitHub Actions, you should make sure you install dependencies and also login to Azure before you publish it.
Here is a job example:
```yml
publish-function:
    name: ⚡ Publish function
    runs-on: ubuntu-latest
    steps:
      # Azure Login
      - name: ☁️🪧 Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Publish App
      - name: ✅ Checkout
        uses: actions/checkout@v3
      - name: 👷‍♂️🛠️ Install Dependencies
        run: npm install # Or whatever type of dependencies installation (or cache download) you have
      - name: ⚡ Publish Function
        run: npx nx publish my-nx-app-name -n my-deployed-func-app-name
```

Let me know if it works or not
